version: "1.0"

x-common-healthcheck: &check_http
  test: ["CMD", "curl", "-f", "http://localhost/", "||", "exit 1"]
  interval: 10s
  timeout: 5s
  retries: 3
  start_period: 10s

volumes:
  database-data:

networks:
  leams-net: 
    external: false
    internal: false
  
services:
  nginx-reverse:
    restart: always
    container_name: nginx-reverse
    image: "nginx:1.29-alpine"
    networks:
      - leams-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key
      - ./nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt
    ports:
      - 8000:443
      - 8080:80
    develop: 
      watch:
        - action: sync
          path: ./nginx.conf
          target: /etc/nginx/nginx.conf
    healthcheck:
      <<: *check_http

  frontend:
    restart: always
    container_name: frontend
    build: ./frontend/
    networks:
      - leams-net
    dns:
      - 8.8.8.8
      - 1.1.1.1
    develop: 
      watch:
        - action: sync
          path: ./frontend/
          target: /frontend
        - action: rebuild
          path: ./frontend/Dockerfile
        - action: rebuild
          path: ./compose.yml
    healthcheck:
      <<: *check_http
  backend-python:
    restart: always
    container_name: backend-python
    build: ./backend/
    networks:
      - leams-net
    environment:
      - SYNC_PSQL=postgresql+psycopg://postgres:secret@database:5432/leams
    dns:
      - 8.8.8.8
      - 1.1.1.1
    develop: 
      watch:
        - action: sync
          path: ./backend/
          target: /backend
        - action: rebuild
          path: ./backend/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      <<: *check_http
  database:
    restart: always
    container_name: database
    image: "postgres:alpine"
    volumes:
      - database-data:/var/lib/postgresql
    networks:
      - leams-net
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - POSTGRES_DB=leams
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NOTE: This nginx's for streaming so better to use another container
  nginx-rtmp:
    restart: always
    container_name: nginx-rtmp
    networks:
      - leams-net
    develop: 
      watch:
        - action: sync
          path: ./nginx.rtmp.conf
          target: /etc/nginx/nginx.conf
        # NOTE: This is for entire compose 
    build: .
    ports:
      - 1935:1935
  # TODO: MUST transfer to zestical because of the https://squidfunk.github.io/mkdocs-material/blog/2026/02/18/mkdocs-2.0/
  docs:
    restart: always
    container_name: docs
    networks:
      - leams-net
    dns:
      - 8.8.8.8
      - 1.1.1.1
    develop: 
      watch:
        - action: sync
          path: ./docs/
          target: /docs
    build: ./docs/
    healthcheck:
      <<: *check_http
  redis:
    restart: always
    container_name: redis
    image: "redis:8.6-alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
# backend-go:
# rabbitmq:

