# WARN: For some distros >1024 is privileged and can't be used for example NixOS
project:
  dir: "/root/Leams"
  accounts:
    # WARN: Mail is required until make captcha bypassing way to sign in a new mail
    mail: 
      email: "testtingdd@gmail.com"
      # If password field in comment it's like None and that means that new account will be created
      password: "MYPASSWORD" # WARN: This field will deleted after success
    vps: 
      # If email is empty than it will be replaced with mail_acc's
      email: "testtingdd@gmail.com"
      # If password field in comment it's like None and that means that new account will be created
      password: "MYPASSWORD" # WARN: This field will deleted after success
      set: false
    domain: 
      # If email is empty than it will be replaced with mail_acc's
      email: "testtingdd@gmail.com"
      # If password field in comment it's like None and that means that new account will be created
      password: "MYPASSWORD" # WARN: This field will deleted after success
      set: false
    cloudflare:
      # If email is empty than it will be replaced with mail_acc's
      email: "testtingdd@gmail.com"
      # If password field in comment it's like None and that means that new account will be created
      password: "MYPASSWORD" # WARN: This field will deleted after success
      set: false
  settings: 
    domain: "leams.tech"
    cloudflare: true
    ip_vps: "144.31.19.248"
  configured: true

server:
  http: 80
  https: 443

services:
  reverse_proxy:
    name: "reverse_proxy"
    port_http: 80
    port_https: 443
    conf_path: '{{ (datasource "config").project.dir }}/infra/nginx/deploy/nginx.conf.template'
    letsencrypt_certs_path: " ./infra/nginx/deploy/data/certbot/letsencrypt"
    letsencrypt_www_path: "./infra/nginx/deploy/data/certbot/www"
    cert_path: '/etc/letsencrypt/live/{{ (datasource "config").project.settings.domain }}/fullchain.pem'
    ssl_key_path: "/etc/letsencrypt/live/project.settings.domain/privkey.pem"

  frontend:
    name: "frontend"
    port: 3000
  backend:
    name: "backend"
    port: 8000
    sub: "api"
  database:
    name: "database"
    port: 5432
    settings:
      - user: "postgres"
      - pass: "secret"
      - host: "database"
      - db: "leams"
  redis:
    name: "redis"
    port: 6379
  docs:
    name: "docs"
    port: 8000
    sub: "docs"
  mobile:
    name: "mobile"
    port: 3000
  stream:
    name: "stream"
    port: 1935
    sub: "stream"


#
# # WARN: Update sub domain in domain seller sites
#
#
# DOMAIN_EMAIL=
#
# #DATABASE
#
