worker_processes  1;

events {
  worker_connections 1024;
}

http {
  server {
    listen              443 ssl;
    http2 on;
    server_name         localhost;
    ssl_certificate     nginx-selfsigned.crt;
    ssl_certificate_key nginx-selfsigned.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    add_header Access-Control-Allow-Origin *;
    location / {
      proxy_pass http://frontend:3000;
    }
  }

  server { 
    listen 80;
    server_name         localhost;
    rewrite ^ https://localhost:8000$request_uri? permanent;
  }

  server { 
    listen 443 ssl;
    http2 on;
    server_name         docs.localhost;
    ssl_certificate     nginx-selfsigned.crt;
    ssl_certificate_key nginx-selfsigned.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    add_header Access-Control-Allow-Origin *;
    location / {
      proxy_pass http://docs:8000;
    }
  }
  server { 
    listen 443 ssl;
    http2 on;
    server_name         mob.localhost;
    ssl_certificate     nginx-selfsigned.crt;
    ssl_certificate_key nginx-selfsigned.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    add_header Access-Control-Allow-Origin *;
    location / {
      proxy_pass http://:8000;
    }
  }
}
