/* tslint:disable */
/* eslint-disable */
/**
 * Contracts
 * My first OpenAPI contracts to link strictly front, back-end parts. Also to give developers and users the whole vision what an endpoint does
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: juchiLee@proton.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AuthGithubPost200Response {
    /**
     * generated with GitHub OAuth 2.0 helping
     */
    'GIT_TOKEN': string;
}
export interface RegisterPost200Response {
    /**
     * generated with GitHub OAuth 2.0 helping
     */
    'GIT_TOKEN': string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * API for generating and sending GitHub token to sign via this one
         * @param {string} clientId Client Id of github
         * @param {string} redierectUri Where user will redierected
         * @param {Code} responseType What type of response will be got
         * @param {Array<string>} scope Which permissions will be granted to user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGithubPost: async (clientId: string, redierectUri: string, responseType: Code, scope: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientId' is not null or undefined
            assertParamExists('authGithubPost', 'clientId', clientId)
            // verify required parameter 'redierectUri' is not null or undefined
            assertParamExists('authGithubPost', 'redierectUri', redierectUri)
            // verify required parameter 'responseType' is not null or undefined
            assertParamExists('authGithubPost', 'responseType', responseType)
            // verify required parameter 'scope' is not null or undefined
            assertParamExists('authGithubPost', 'scope', scope)
            const localVarPath = `/auth/github`
                .replace(`{${"client_id"}}`, encodeURIComponent(String(clientId)))
                .replace(`{${"redierect_uri"}}`, encodeURIComponent(String(redierectUri)))
                .replace(`{${"response_type"}}`, encodeURIComponent(String(responseType)))
                .replace(`{${"scope"}}`, encodeURIComponent(String(scope)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Getting from backend(S3) videos via recommendations
         * @param {string} authorization value must be &#x60;Bearer &lt;token&gt;&#x60; where &#x60;&lt;token&gt;&#x60; is api key prefixed with cal_
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mainVideosCategoriesGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('mainVideosCategoriesGet', 'authorization', authorization)
            const localVarPath = `/main/videos/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * API for creating new user and after logging it after this
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * API for generating and sending GitHub token to sign via this one
         * @param {string} clientId Client Id of github
         * @param {string} redierectUri Where user will redierected
         * @param {Code} responseType What type of response will be got
         * @param {Array<string>} scope Which permissions will be granted to user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authGithubPost(clientId: string, redierectUri: string, responseType: Code, scope: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthGithubPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authGithubPost(clientId, redierectUri, responseType, scope, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.authGithubPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Getting from backend(S3) videos via recommendations
         * @param {string} authorization value must be &#x60;Bearer &lt;token&gt;&#x60; where &#x60;&lt;token&gt;&#x60; is api key prefixed with cal_
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mainVideosCategoriesGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mainVideosCategoriesGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.mainVideosCategoriesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * API for creating new user and after logging it after this
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegisterPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.registerPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * API for generating and sending GitHub token to sign via this one
         * @param {string} clientId Client Id of github
         * @param {string} redierectUri Where user will redierected
         * @param {Code} responseType What type of response will be got
         * @param {Array<string>} scope Which permissions will be granted to user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGithubPost(clientId: string, redierectUri: string, responseType: Code, scope: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<AuthGithubPost200Response> {
            return localVarFp.authGithubPost(clientId, redierectUri, responseType, scope, options).then((request) => request(axios, basePath));
        },
        /**
         * Getting from backend(S3) videos via recommendations
         * @param {string} authorization value must be &#x60;Bearer &lt;token&gt;&#x60; where &#x60;&lt;token&gt;&#x60; is api key prefixed with cal_
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mainVideosCategoriesGet(authorization: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.mainVideosCategoriesGet(authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * API for creating new user and after logging it after this
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerPost(options?: RawAxiosRequestConfig): AxiosPromise<RegisterPost200Response> {
            return localVarFp.registerPost(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * API for generating and sending GitHub token to sign via this one
     * @param {string} clientId Client Id of github
     * @param {string} redierectUri Where user will redierected
     * @param {Code} responseType What type of response will be got
     * @param {Array<string>} scope Which permissions will be granted to user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authGithubPost(clientId: string, redierectUri: string, responseType: Code, scope: Array<string>, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authGithubPost(clientId, redierectUri, responseType, scope, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Getting from backend(S3) videos via recommendations
     * @param {string} authorization value must be &#x60;Bearer &lt;token&gt;&#x60; where &#x60;&lt;token&gt;&#x60; is api key prefixed with cal_
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public mainVideosCategoriesGet(authorization: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).mainVideosCategoriesGet(authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * API for creating new user and after logging it after this
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registerPost(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).registerPost(options).then((request) => request(this.axios, this.basePath));
    }
}



