/* tslint:disable */
/* eslint-disable */
/**
 * Contracts
 * My first OpenAPI contracts to link strictly front, back-end parts. Also to give developers and users the whole vision what an endpoint does
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: juchiLee@proton.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

