foreground = yes

[rtmps]
accept = ${NGINX_STREAM_PORT}
connect = ${COMPOSE_NGINX_RTMP_NAME}:${NGINX_RTMP_PORT}
cert = ${NGINX_SSL_CERT_PATH}
key  = ${NGINX_SSL_KEY_PATH}
sslVersion = TLSv1.2
sslVersionMax = TLSv1.3
options = NO_SSLv2
options = NO_SSLv3
