# coding: utf-8

"""
    Contracts

    My first OpenAPI contracts to link strictly front, back-end parts. Also to give developers and users the whole vision what an endpoint does

    The version of the OpenAPI document: 1.0.1
    Contact: juchiLee@proton.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Contracts",
    description="My first OpenAPI contracts to link strictly front, back-end parts. Also to give developers and users the whole vision what an endpoint does",
    version="1.0.1",
)

app.include_router(DefaultApiRouter)
