import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UpSide } from "./_components/nav-section//UpSide";
import { MainLogin } from "./_components/auth-section/auth-block";
import { LeftSide } from "./_components/left-section/left-main";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<MainLogin />
				<div className="h-screen">
					<UpSide />
					<div className="inline-flex h-full w-full">
						<LeftSide />
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
